dcConsData = [
	{name:"1.gif", keywords:["우리핵안녕"], tags:["우리핵"]},
	{name:"2.gif", keywords:["우리핵아닌데"], tags:["우리핵"]},
	{name:"3.gif", keywords:["우리핵박수"], tags:["우리핵"]},
	{name:"4.gif", keywords:["우리핵박수2"], tags:["우리핵"]},
	{name:"5.gif", keywords:["우리핵박수3"], tags:["우리핵"]},
	{name:"6.gif", keywords:["우리핵드럼"], tags:["우리핵"]},
	{name:"7.gif", keywords:["우리핵빵야"], tags:["우리핵"]},
	{name:"8.gif", keywords:["우리핵투정"], tags:["우리핵"]},
	{name:"9.gif", keywords:["우리핵쌍안경"], tags:["우리핵"]},
	{name:"10.gif", keywords:["우리핵확대"], tags:["우리핵"]},
	{name:"11.gif", keywords:["우리핵생각"], tags:["우리핵"]},
	{name:"12.gif", keywords:["스탈", "스탈린", "리듬스탈"], tags:["리듬스탈"]},
	{name:"13.png", keywords:["크크따봉", "따봉"], tags:["크크따봉"]},
	{name:"14.gif", keywords:["관짝준비"], tags:["관짝"]},
	{name:"15.gif", keywords:["관짝댄스"], tags:["관짝"]},
	{name:"16.gif", keywords:["관짝댄스2"], tags:["관짝"]},
	{name:"17.gif", keywords:["매트릭스" ,"매트", "매트릭"], tags:["매트릭스"]},
	{name:"18.gif", keywords:["스미스", "스미"], tags:["매트릭스"]},
	{name:"19.gif", keywords:["회피", "회"], tags:["매트릭스"]},
	{name:"20.gif", keywords:["회피2", "회"], tags:["매트릭스"]},
	{name:"21.gif", keywords:["팝콘"], tags:["기타"]},
	{name:"22.png", keywords:["핫산발상", "발상"], tags:["핫산"]},
	{name:"23.png", keywords:["핫산펑", "펑"], tags:["핫산"]},
	{name:"24.png", keywords:["핫산쾅", "쾅"], tags:["핫산"]},
	{name:"25.png", keywords:["마참내"], tags:["달걀"]},
	{name:"26.png", keywords:["시간절약"], tags:["달걀"]},
	{name:"27.png", keywords:["즐겁다"], tags:["달걀"]},
	{name:"28.png", keywords:["손도깔끔"], tags:["달걀"]},
	{name:"29.png", keywords:["세종대왕"], tags:["기타"]},
	{name:"30.png", keywords:["읒증"], tags:["기타"]},
	{name:"31.png", keywords:["인텔"], tags:["기타"]},
	{name:"32.png", keywords:["암드"], tags:["기타"]},
	{name:"33.png", keywords:["라이젠"], tags:["기타"]},
	{name:"34.gif", keywords:["리사수"], tags:["기타"]},
	{name:"35.gif", keywords:["리샤수"], tags:["기타"]},
	{name:"36.gif", keywords:["자랑수"], tags:["기타"]},
	{name:"37.gif", keywords:["클럽수"], tags:["기타"]},
	{name:"38.gif", keywords:["힙사수"], tags:["기타"]},
	{name:"39.png", keywords:["스택플로"], tags:["기타"]},
	{name:"40.gif", keywords:["타이핑"], tags:["기타"]},
	{name:"41.gif", keywords:["프로그래밍"], tags:["기타"]},
	{name:"42.png", keywords:["코주부놀람"], tags:["기타"]},
	{name:"43.png", keywords:["코주부한심"], tags:["기타"]},
	{name:"44.gif", keywords:["문풍당당"], tags:["당당"]},
	{name:"45.gif", keywords:["문풍당당2"], tags:["당당"]},
	{name:"46.gif", keywords:["문풍당당3"], tags:["당당"]},
	{name:"47.gif", keywords:["문풍당당4"], tags:["당당"]},
	{name:"48.gif", keywords:["문풍당당5"], tags:["당당"]},
	{name:"49.gif", keywords:["문풍당당6"], tags:["당당"]},
	{name:"50.gif", keywords:["이풍당당"], tags:["당당"]},
	{name:"51.gif", keywords:["이풍당당2"], tags:["당당"]},
	{name:"52.gif", keywords:["이풍당당3"], tags:["당당"]},
	{name:"53.gif", keywords:["예풍당당"], tags:["당당"]},
	{name:"54.png", keywords:["이지붐"], tags:["기타"]},
	{name:"55.gif", keywords:["댕댕콘"], tags:["기타"]},
	{name:"56.gif", keywords:["펄럭"], tags:["기타"]},
	{name:"57.gif", keywords:["펄럭2"], tags:["기타"]},
	{name:"58.png", keywords:["태극기"], tags:["기타"]},
	{name:"59.png", keywords:["무궁화"], tags:["기타"]},
	{name:"60.png", keywords:["무궁화2"], tags:["기타"]},
	{name:"61.png", keywords:["눈물너클즈"], tags:["기타"]},
	{name:"62.png", keywords:["눈물소닉"], tags:["기타"]},
	{name:"63.png", keywords:["눈물에이미"], tags:["기타"]},
	{name:"64.png", keywords:["눈물테일즈"], tags:["기타"]},
	{name:"65.png", keywords:["소닉붐"], tags:["기타"]},
	{name:"66.png", keywords:["싸닉"], tags:["기타"]},
	{name:"67.png", keywords:["골든싸닉"], tags:["기타"]},
	{name:"68.png", keywords:["따일즈"], tags:["기타"]},
	{name:"69.png", keywords:["나클즈"], tags:["기타"]},
	{name:"70.png", keywords:["싸도우"], tags:["기타"]},
	{name:"71.png", keywords:["리얼싸닉"], tags:["기타"]},
	{name:"72.png", keywords:["스웨그싸닉"], tags:["기타"]},
	{name:"73.png", keywords:["싸닉매니아"], tags:["기타"]},
	{name:"74.gif", keywords:["식은땀"], tags:["기타"]},
	{name:"75.gif", keywords:["댄스로이"], tags:["기타"]},
	{name:"76.gif", keywords:["회전잇님"], tags:["기타"]},
	{name:"77.gif", keywords:["광클"], tags:["기타"]},
	{name:"78.png", keywords:["냥슬픔"], tags:["마작", "작혼"]},
	{name:"79.png", keywords:["냥경악"], tags:["마작", "작혼"]},
	{name:"80.gif", keywords:["냥경악2"], tags:["기타"]},
	{name:"81.gif", keywords:["냥경악3"], tags:["기타"]},
	{name:"82.gif", keywords:["냥정색"], tags:["기타"]},
	{name:"83.gif", keywords:["냥확대"], tags:["기타"]},
	{name:"84.png", keywords:["페페흐음"], tags:["개구리"]},
	{name:"85.png", keywords:["페페발암"], tags:["개구리"]},
	{name:"86.png", keywords:["페페따봉"], tags:["개구리"]},
	{name:"87.gif", keywords:["페바"], tags:["개구리"]},
	{name:"88.png", keywords:["화난페페"], tags:["개구리"]},
	{name:"89.png", keywords:["앵그리페페"], tags:["개구리"]},
	{name:"90.png", keywords:["앵그리페페2"], tags:["개구리"]},
	{name:"91.png", keywords:["페페허"], tags:["개구리"]},
	{name:"92.png", keywords:["페페헉"], tags:["개구리"]},
	{name:"93.png", keywords:["페페헐"], tags:["개구리"]},
	{name:"94.png", keywords:["페페기대"], tags:["개구리"]},
	{name:"95.png", keywords:["페페봉기"], tags:["개구리"]},
	{name:"96.png", keywords:["페페물음표"], tags:["개구리"]},
	{name:"97.gif", keywords:["페페빼액"], tags:["개구리"]},
	{name:"98.gif", keywords:["페페우울"], tags:["개구리"]},
	{name:"99.png", keywords:["페페멋짐"], tags:["개구리"]},
	{name:"100.png", keywords:["페페자살"], tags:["개구리"]},
	{name:"101.png", keywords:["페페놀람"], tags:["개구리"]},
	{name:"102.png", keywords:["페페띠용"], tags:["개구리"]},
	{name:"103.png", keywords:["페페모자"], tags:["개구리"]},
	{name:"104.png", keywords:["페페초딩"], tags:["개구리"]},
	{name:"105.gif", keywords:["페페팝콘"], tags:["개구리"]},
	{name:"106.png", keywords:["페페VR"], tags:["개구리"]},
	{name:"107.gif", keywords:["페페박수"], tags:["개구리"]},
	{name:"108.png", keywords:["페페예스"], tags:["개구리"]},
	{name:"109.png", keywords:["페페노"], tags:["개구리"]},
	{name:"110.png", keywords:["페페경악"], tags:["개구리"]},
	{name:"111.gif", keywords:["페페댄스"], tags:["개구리"]},
	{name:"112.gif", keywords:["페페손씻", "페페손닦"], tags:["개구리"]},
	{name:"113.gif", keywords:["제리하이"], tags:["톰과제리"]},
	{name:"114.gif", keywords:["제리폭소"], tags:["톰과제리"]},
	{name:"115.gif", keywords:["제리핥짝"], tags:["톰과제리"]},
	{name:"116.gif", keywords:["제리하트"], tags:["톰과제리"]},
	{name:"117.gif", keywords:["제리감사"], tags:["톰과제리"]},
	{name:"118.gif", keywords:["톰감사"], tags:["톰과제리"]},
	{name:"119.gif", keywords:["톰박수"], tags:["톰과제리"]},
	{name:"120.gif", keywords:["톰괭이"], tags:["톰과제리"]},
	{name:"121.gif", keywords:["톰반대"], tags:["톰과제리"]},
	{name:"122.gif", keywords:["톰찬성"], tags:["톰과제리"]},
	{name:"123.gif", keywords:["톰띠용"], tags:["톰과제리"]},
	{name:"124.png", keywords:["그건니가"], tags:["기타"]},
	{name:"125.png", keywords:["흠"], tags:["흠"]},
	{name:"126.png", keywords:["스웩흠"], tags:["흠"]},
	{name:"127.png", keywords:["흠흠흠"], tags:["흠"]},
	{name:"128.gif", keywords:["혼란흠"], tags:["흠"]},
	{name:"129.gif", keywords:["회전흠"], tags:["흠"]},
	{name:"130.gif", keywords:["회전흠2"], tags:["흠"]},
	{name:"131.gif", keywords:["회전흠3"], tags:["흠"]},
	{name:"132.png", keywords:["저퀄흠"], tags:["흠"]},
	{name:"133.png", keywords:["고퀄흠"], tags:["흠"]},
	{name:"134.gif", keywords:["왜곡흠"], tags:["흠"]},
	{name:"135.gif", keywords:["눈물앵무"], tags:["앵무"]},
	{name:"136.gif", keywords:["혼란앵무"], tags:["앵무"]},
	{name:"137.gif", keywords:["더블앵무"], tags:["앵무"]},
	{name:"138.gif", keywords:["머니앵무"], tags:["앵무"]},
	{name:"139.gif", keywords:["산타앵무"], tags:["앵무"]},
	{name:"140.gif", keywords:["스핀앵무"], tags:["앵무"]},
	{name:"141.gif", keywords:["팝콘앵무"], tags:["앵무"]},
	{name:"142.gif", keywords:["문워크앵무"], tags:["앵무"]},
	{name:"143.gif", keywords:["호랑이"], tags:["기타"]},
	{name:"144.gif", keywords:["호랑이2"], tags:["기타"]},
	{name:"145.gif", keywords:["호랑이3"], tags:["기타"]},
	{name:"146.gif", keywords:["호랑이4"], tags:["기타"]},
	{name:"147.png", keywords:["인공지능"], tags:["기타"]},
	{name:"148.gif", keywords:["버그"], tags:["기타"]},
	{name:"149.gif", keywords:["꼬우면"], tags:["기타"]},
	{name:"150.gif", keywords:["의도된"], tags:["기타"]},
	{name:"151.png", keywords:["나나따봉"], tags:["마작", "작혼"]},
	{name:"152.png", keywords:["나나반칙", "나나삐익"], tags:["마작", "작혼"]},
	{name:"153.png", keywords:["나나죽어"], tags:["마작", "작혼"]},
	{name:"154.png", keywords:["나나흑흑", "나나눈물"], tags:["마작", "작혼"]},
	{name:"155.png", keywords:["나데꿀꺽"], tags:["마작", "작혼"]},
	{name:"156.png", keywords:["나데맥주"], tags:["마작", "작혼"]},
	{name:"157.png", keywords:["나데찡긋"], tags:["마작", "작혼"]},
	{name:"158.png", keywords:["나데흥미", "흥미로워"], tags:["마작", "작혼"]},
	{name:"159.png", keywords:["나츠키돈"], tags:["마작", "작혼"]},
	{name:"160.png", keywords:["나츠키풉", "나츠기웃음"], tags:["마작", "작혼"]},
	{name:"161.png", keywords:["나츠키흑염룡"], tags:["마작", "작혼"]},
	{name:"162.png", keywords:["나츠기흠"], tags:["마작", "작혼"]},
	{name:"163.gif", keywords:["냥따봉"], tags:["마작", "작혼"]},
	{name:"164.png", keywords:["냥빠직"], tags:["마작", "작혼"]},
	{name:"165.png", keywords:["냥와장창"], tags:["마작", "작혼"]},
	{name:"166.png", keywords:["냥찌릿", "냥째릿"], tags:["마작", "작혼"]},
	{name:"167.png", keywords:["리우벽쾅", "리우화남"], tags:["마작", "작혼"]},
	{name:"168.png", keywords:["리우뿌듯"], tags:["마작", "작혼"]},
	{name:"169.png", keywords:["리우짜증"], tags:["마작", "작혼"]},
	{name:"170.png", keywords:["리우한숨"], tags:["마작", "작혼"]},
	{name:"171.png", keywords:["마이기도", "마이쯔모", "쯔모"], tags:["마작", "작혼"]},
	{name:"172.png", keywords:["마이덜덜"], tags:["마작", "작혼"]},
	{name:"173.png", keywords:["마이유령"], tags:["마작", "작혼"]},
	{name:"174.png", keywords:["마이흑흑"], tags:["마작", "작혼"]},
	{name:"175.png", keywords:["멍시무룩"], tags:["마작", "작혼"]},
	{name:"176.png", keywords:["멍갈고리", "멍물음표"], tags:["마작", "작혼"]},
	{name:"177.png", keywords:["멍초롱"], tags:["마작", "작혼"]},
	{name:"178.png", keywords:["멍하품"], tags:["마작", "작혼"]},
	{name:"179.png", keywords:["미키미안"], tags:["마작", "작혼"]},
	{name:"180.png", keywords:["미키식칼"], tags:["마작", "작혼"]},
	{name:"181.png", keywords:["미키칼식"], tags:["마작", "작혼"]},
	{name:"182.png", keywords:["미키바게트", "바게트"], tags:["마작", "작혼"]},
	{name:"183.png", keywords:["미키광선검", "광선검"], tags:["마작", "작혼"]},
	{name:"184.png", keywords:["미키풉"], tags:["마작", "작혼"]},
	{name:"185.png", keywords:["미키홀짝"], tags:["마작", "작혼"]},
	{name:"186.png", keywords:["사라기절"], tags:["마작", "작혼"]},
	{name:"187.png", keywords:["사라얼음"], tags:["마작", "작혼"]},
	{name:"188.png", keywords:["사라쿨쿨"], tags:["마작", "작혼"]},
	{name:"189.png", keywords:["사라풉"], tags:["마작", "작혼"]},
	{name:"190.png", keywords:["소라각혈"], tags:["마작", "작혼"]},
	{name:"191.png", keywords:["소라니가"], tags:["마작", "작혼"]},
	{name:"192.png", keywords:["소라빠직"], tags:["마작", "작혼"]},
	{name:"193.png", keywords:["소라흑흑"], tags:["마작", "작혼"]},
	{name:"194.png", keywords:["안즈브이", "안즈v", "안즈V"], tags:["마작", "작혼"]},
	{name:"195.png", keywords:["안즈따봉"], tags:["마작", "작혼"]},
	{name:"196.png", keywords:["안즈지갑"], tags:["마작", "작혼"]},
	{name:"197.png", keywords:["안즈코피"], tags:["마작", "작혼"]},
	{name:"198.png", keywords:["오사무끄덕"], tags:["마작", "작혼"]},
	{name:"199.png", keywords:["오사무니가"], tags:["마작", "작혼"]},
	{name:"200.png", keywords:["오사무짜증"], tags:["마작", "작혼"]},
	{name:"201.png", keywords:["오사무충격"], tags:["마작", "작혼"]},
	{name:"202.png", keywords:["유이권총"], tags:["마작", "작혼"]},
	{name:"203.png", keywords:["유이따봉"], tags:["마작", "작혼"]},
	{name:"204.png", keywords:["유이신고", "유이경찰", "유이FBI", "신고", "경찰"], tags:["마작", "작혼"]},
	{name:"205.png", keywords:["유이역따봉"], tags:["마작", "작혼"]},
	{name:"206.png", keywords:["유이찌릿"], tags:["마작", "작혼"]},
	{name:"207.png", keywords:["조셉뿌듯"], tags:["마작", "작혼"]},
	{name:"208.png", keywords:["조셉시무룩"], tags:["마작", "작혼"]},
	{name:"209.png", keywords:["조셉음흉"], tags:["마작", "작혼"]},
	{name:"210.png", keywords:["조셉흠"], tags:["마작", "작혼"]},
	{name:"211.png", keywords:["지니아발상"], tags:["마작", "작혼"]},
	{name:"212.png", keywords:["지니아이의", "이의있음"], tags:["마작", "작혼"]},
	{name:"213.png", keywords:["지니아스웩"], tags:["마작", "작혼"]},
	{name:"214.png", keywords:["지니아풉", "지니아소근"], tags:["마작", "작혼"]},
	{name:"215.png", keywords:["지니아흠"], tags:["마작", "작혼"]},
	{name:"216.png", keywords:["치오리냠냠"], tags:["마작", "작혼"]},
	{name:"217.png", keywords:["치오리띠용"], tags:["마작", "작혼"]},
	{name:"218.png", keywords:["치오리아야야", "아야야"], tags:["마작", "작혼"]},
	{name:"219.png", keywords:["치오리흑흑"], tags:["마작", "작혼"]},
	{name:"220.png", keywords:["카나경멸"], tags:["마작", "작혼"]},
	{name:"221.png", keywords:["카나띠용"], tags:["마작", "작혼"]},
	{name:"222.png", keywords:["카나스위치"], tags:["마작", "작혼"]},
	{name:"223.png", keywords:["카나흑흑"], tags:["마작", "작혼"]},
	{name:"224.png", keywords:["카비1판", "1판", "단한판", "한판"], tags:["마작", "작혼"]},
	{name:"225.png", keywords:["카비놀람"], tags:["마작", "작혼"]},
	{name:"226.png", keywords:["카비부끄"], tags:["마작", "작혼"]},
	{name:"227.png", keywords:["카비히히"], tags:["마작", "작혼"]},
	{name:"228.png", keywords:["카비요가"], tags:["마작", "작혼"]},
	{name:"229.png", keywords:["케이쿠감자", "감자", "주먹감자"], tags:["마작", "작혼"]},
	{name:"230.png", keywords:["케이쿠놀람", "케이쿠띠용"], tags:["마작", "작혼"]},
	{name:"231.png", keywords:["케이쿠컨닝", "컨닝"], tags:["마작", "작혼"]},
	{name:"232.png", keywords:["케이쿠쿨쿨"], tags:["마작", "작혼"]},
	{name:"233.png", keywords:["하나심한말", "야발"], tags:["마작", "작혼"]},
	{name:"234.png", keywords:["하나질문"], tags:["마작", "작혼"]},
	{name:"235.png", keywords:["하나탐정"], tags:["마작", "작혼"]},
	{name:"236.png", keywords:["하나번떡", "하나번쩍"], tags:["마작", "작혼"]},
	{name:"237.png", keywords:["하루나갈고리", "하루나물음표"], tags:["마작", "작혼"]},
	{name:"238.png", keywords:["하루나깡", "깡", "하루나캉", "캉"], tags:["마작", "작혼"]},
	{name:"239.png", keywords:["하루나불편"], tags:["마작", "작혼"]},
	{name:"240.png", keywords:["하루나아하"], tags:["마작", "작혼"]},
	{name:"241.png", keywords:["히나타놀람"], tags:["마작", "작혼"]},
	{name:"242.png", keywords:["히나타신고", "히나타경찰", "히타나FBI", "철컹", "히나타철컹"], tags:["마작", "작혼"]},
	{name:"243.png", keywords:["하나타포기"], tags:["마작", "작혼"]},
	{name:"244.png", keywords:["하나타흠", "히나타음"], tags:["마작", "작혼"]},
	{name:"245.png", keywords:["치오리두근"], tags:["마작", "작혼"]},
	{name:"246.png", keywords:["자동쯔모기리", "자동쯔모", "쯔모기리", "자쯔기", "기리머신"], tags:["마작", "작혼"]},
	{name:"247.png", keywords:["혼란냥이"], tags:["기타"]},
	{name:"248.png", keywords:["우주흠", "태양흠", "흐음"], tags:["기타"]},
	{name:"249.png", keywords:["댕댕스웩"], tags:["기타"]},
	{name:"250.png", keywords:["냥불안"], tags:["마작", "작혼"]},
	{name:"254.png", keywords:["마이식칼"], tags:["마작", "작혼"]},
	{name:"255.png", keywords:["1만", "일만"], tags:["마작", "작혼"]},
	{name:"256.png", keywords:["2만", "이만"], tags:["마작", "작혼"]},
	{name:"257.png", keywords:["3만", "삼만"], tags:["마작", "작혼"]},
	{name:"258.png", keywords:["4만", "사만"], tags:["마작", "작혼"]},
	{name:"259.png", keywords:["5만", "오만"], tags:["마작", "작혼"]},
	{name:"260.png", keywords:["6만", "육만"], tags:["마작", "작혼"]},
	{name:"261.png", keywords:["7만", "칠만"], tags:["마작", "작혼"]},
	{name:"262.png", keywords:["8만", "팔만"], tags:["마작", "작혼"]},
	{name:"263.png", keywords:["9만", "구만"], tags:["마작", "작혼"]},
	{name:"264.png", keywords:["5만도라", "오만도라", "적5만", "적오만", "적다섯만"], tags:["마작", "작혼"]},
	{name:"265.png", keywords:["1통", "일통"], tags:["마작", "작혼"]},
	{name:"266.png", keywords:["2통", "이통"], tags:["마작", "작혼"]},
	{name:"267.png", keywords:["3통", "삼통"], tags:["마작", "작혼"]},
	{name:"268.png", keywords:["4통", "사통"], tags:["마작", "작혼"]},
	{name:"269.png", keywords:["5통", "오통"], tags:["마작", "작혼"]},
	{name:"270.png", keywords:["6통", "육통"], tags:["마작", "작혼"]},
	{name:"271.png", keywords:["7통", "칠통"], tags:["마작", "작혼"]},
	{name:"272.png", keywords:["8통", "팔통"], tags:["마작", "작혼"]},
	{name:"273.png", keywords:["9통", "구통"], tags:["마작", "작혼"]},
	{name:"274.png", keywords:["적5통도라", "오통도라", "적5통", "적오통", "적다섯통"], tags:["마작", "작혼"]},
	{name:"275.png", keywords:["1삭", "일삭"], tags:["마작", "작혼"]},
	{name:"276.png", keywords:["2삭", "이삭"], tags:["마작", "작혼"]},
	{name:"277.png", keywords:["3삭", "삼삭"], tags:["마작", "작혼"]},
	{name:"292.png", keywords:["4삭", "사삭"], tags:["마작", "작혼"]},
	{name:"278.png", keywords:["5삭", "오삭"], tags:["마작", "작혼"]},
	{name:"279.png", keywords:["6삭", "육삭"], tags:["마작", "작혼"]},
	{name:"280.png", keywords:["7삭", "칠삭"], tags:["마작", "작혼"]},
	{name:"281.png", keywords:["8삭", "팔삭"], tags:["마작", "작혼"]},
	{name:"282.png", keywords:["9삭", "구삭"], tags:["마작", "작혼"]},
	{name:"283.png", keywords:["적5삭도라", "오삭도라", "적5삭", "적오삭", "적다섯삭"], tags:["마작", "작혼"]},
	{name:"284.png", keywords:["동", "동패"], tags:["마작", "작혼"]},
	{name:"285.png", keywords:["남", "남패"], tags:["마작", "작혼"]},
	{name:"286.png", keywords:["서", "서패"], tags:["마작", "작혼"]},
	{name:"287.png", keywords:["북", "북패"], tags:["마작", "작혼"]},
	{name:"288.png", keywords:["백", "백패", "두부"], tags:["마작", "작혼"]},
	{name:"289.png", keywords:["발", "발패"], tags:["마작", "작혼"]},
	{name:"290.png", keywords:["중", "중패"], tags:["마작", "작혼"]},
	{name:"291.png", keywords:["뒷면", "패"], tags:["마작", "작혼"]},

];
var originalAddChatMessage = addChatMessage;
addChatMessage = function(nick, message, data) {
  var chat = originalAddChatMessage(nick, message, data);
  chat.style.top = Math.random() * 90 + '%';
  if (data.color && configData.personalColor) {
    chat.lower.msg.style.color = data.color;
  }
  return chat;
}